update workflow and skipif execution

diff --git a/.github/workflows/WindowsRelease.yml b/.github/workflows/WindowsRelease.yml
--- a/.github/workflows/WindowsRelease.yml
+++ b/.github/workflows/WindowsRelease.yml
@@ -41,7 +41,7 @@ jobs:
           Start-Process -FilePath "$qgisExec" -ArgumentList "download_extra_packages_class.py" -NoNewWindow -Wait
           $env:PYTHONPATH = "$env:PYTHONPATH;APPDATA\QGIS\QGIS3\profiles\default\python\plugins"
           Set-Location "$pluginPath"
-          Start-Process -FilePath "$qgisExec" -ArgumentList "-m pytest test" -NoNewWindow -Wait
+          Start-Process -FilePath "$qgisExec" -ArgumentList "-m pytest test --report-log=.\log.jsonl" -NoNewWindow -Wait
 
       - name: Setup and test plugin on LTR
         shell: pwsh
@@ -60,9 +60,19 @@ jobs:
           Start-Process -FilePath "$qgisExec" -ArgumentList "download_extra_packages_class.py" -NoNewWindow -Wait
           $env:PYTHONPATH = "$env:PYTHONPATH;APPDATA\QGIS\QGIS3\profiles\default\python\plugins"
           Set-Location "$pluginPath"
-          Start-Process -FilePath "$qgisExec" -ArgumentList "-m pytest test" -NoNewWindow -Wait
+          Start-Process -FilePath "$qgisExec" -ArgumentList "-m pytest test --report-log=$pluginPath\log.jsonl" -NoNewWindow -Wait
 
       - name: Check packages installed
         shell: pwsh
         run: |
-          Get-ChildItem -Path "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae" -Name
+          Get-ChildItem -Path "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae\packages" -Name
+
+      - name: Check if tests failed
+        shell: pwsh
+        run: |
+          $pluginPath = "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins"
+          $fails = Select-String -Path .\*.jsonl -Pattern 'failed'
+          if ($fails.Matches.Length -gt 0) {
+              Write-Error "Check for errors in the tests run"
+              exit 1
+          }
